[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "svsm-target.json"
rustflags = ["-C", "force-frame-pointers", "--cfg", "aes_force_soft", "--cfg", "polyval_force_soft"]

